name: Build this project with gradle

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Install libtool
      - uses: actions/checkout@v4
        with:
          repository: openvenues/libpostal
          path: libpostal
          run: |
            ./bootstrap.sh
            mkdir data_dir
            ./configure --datadir=`pwd`/data_dir MODEL=senzing
            sudo make -j4
            sudo make install
            sudo ldconfig
      - name: Assemble project
        uses: actions/checkout@v4
        with:
          repository: Qualytics/jpostal
          path: jpostal
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew assemble