name: Build this project with gradle

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Install libtool
        run: |
          sudo apt-get update
          sudo apt-get install build-essential curl autoconf automake libtool pkg-config git
          git clone https://github.com/openvenues/libpostal
          cd libpostal
          ./bootstrap.sh
          mkdir data_dir
          ./configure --datadir=`pwd`/data_dir MODEL=senzing
          sudo make -j4
          sudo make install
          sudo ldconfig
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew assemble